services:
  minio:
    restart: always 
    container_name: minio
    image: quay.io/minio/minio:latest	
    environment:
      - MINIO_ROOT_USER=dlab-backend
      - MINIO_ROOT_PASSWORD=dlab-backend-secret
    ports:
      - '9002:9000'
      - '9001:9090'
    volumes:
      - ./backup/:/data
    command: server /data --console-address ":9090"
